insert into authors (name) values ('Абгарян Наринэ');
insert into authors (name) values ('Байбаков Иван');
insert into authors (name) values ('Байер Уильям');
insert into authors (name) values ('Бакиров Анвар');
insert into authors (name) values ('Бакман Фредрик');
insert into books (author, title, priceOld, price) values (1, 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author, title, priceOld, price) values (1, 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author, title, priceOld, price) values (1, 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author, title, priceOld, price) values (1, 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author, title, priceOld, price) values (1, 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author, title, priceOld, price) values (2, 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author, title, priceOld, price) values (2, 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author, title, priceOld, price) values (2, 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author, title, priceOld, price) values (2, 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author, title, priceOld, price) values (2, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author, title, priceOld, price) values (3, 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author, title, priceOld, price) values (3, 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author, title, priceOld, price) values (3, 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author, title, priceOld, price) values (3, 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author, title, priceOld, price) values (3, 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author, title, priceOld, price) values (4, 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author, title, priceOld, price) values (4, 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author, title, priceOld, price) values (4, 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author, title, priceOld, price) values (4, 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author, title, priceOld, price) values (4, 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author, title, priceOld, price) values (5, 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author, title, priceOld, price) values (5, 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author, title, priceOld, price) values (5, 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author, title, priceOld, price) values (5, 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author, title, priceOld, price) values (5, 'facilitate efficient eyeballs', '$232.30', '$131.48');
